### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by alecive** [trey0/zmdp#1]
Hey @trey0 , 

I was trying to get more information on ZMDP but the link you provide in the `README.md` (i.e. this one http://www.cs.cmu.edu/~trey/zmdp ) returns a 403 forbidden. 

Do you have anywhere else to point me to?

**Comment by trey0** [comment]
http://longhorizon.org/trey/zmdp/

Thanks for the note. -T

**Comment by alecive** [comment]
Thank you @trey0 ! :+1:
